"""add file_type to files

Revision ID: 4538da984898
Revises: 3d684d7bd308
Create Date: 2025-12-14 13:08:44.269228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4538da984898'
down_revision: Union[str, Sequence[str], None] = '3d684d7bd308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_type', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 'files', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'file_type')
    # ### end Alembic commands ###
