"""create projects table

Revision ID: d27376d3895e
Revises: c219b7b34f03
Create Date: 2025-11-08 12:12:12.305212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd27376d3895e'
down_revision: Union[str, Sequence[str], None] = 'c219b7b34f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('subject', sa.String(length=100), nullable=False))
    op.add_column('projects', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('status', mysql.ENUM('OPEN', 'CLOSED'), server_default='OPEN', nullable=False))
    op.add_column('projects', sa.Column('file_key', sa.String(length=255), nullable=True))
    op.alter_column('projects', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('projects', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('projects', 'deadline',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('projects', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('projects', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_index('ix_projects_course', table_name='projects')
    op.drop_index('ix_projects_deadline', table_name='projects')
    op.drop_index('ix_projects_id', table_name='projects')
    op.drop_index('ix_projects_name', table_name='projects')
    op.drop_column('projects', 'course')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('course', mysql.VARCHAR(length=128), nullable=True))
    op.create_index('ix_projects_name', 'projects', ['name'], unique=False)
    op.create_index('ix_projects_id', 'projects', ['id'], unique=False)
    op.create_index('ix_projects_deadline', 'projects', ['deadline'], unique=False)
    op.create_index('ix_projects_course', 'projects', ['course'], unique=False)
    op.alter_column('projects', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('projects', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('projects', 'deadline',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('projects', 'name',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('projects', 'id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('projects', 'file_key')
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'description')
    op.drop_column('projects', 'subject')
    # ### end Alembic commands ###
